// Generated by gencpp from file jami7095_hw2/EchoString.msg
// DO NOT EDIT!


#ifndef JAMI7095_HW2_MESSAGE_ECHOSTRING_H
#define JAMI7095_HW2_MESSAGE_ECHOSTRING_H

#include <ros/service_traits.h>


#include <jami7095_hw2/EchoStringRequest.h>
#include <jami7095_hw2/EchoStringResponse.h>


namespace jami7095_hw2
{

struct EchoString
{

typedef EchoStringRequest Request;
typedef EchoStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EchoString
} // namespace jami7095_hw2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jami7095_hw2::EchoString > {
  static const char* value()
  {
    return "e478228380bb2631fd59d58e07666a92";
  }

  static const char* value(const ::jami7095_hw2::EchoString&) { return value(); }
};

template<>
struct DataType< ::jami7095_hw2::EchoString > {
  static const char* value()
  {
    return "jami7095_hw2/EchoString";
  }

  static const char* value(const ::jami7095_hw2::EchoString&) { return value(); }
};


// service_traits::MD5Sum< ::jami7095_hw2::EchoStringRequest> should match
// service_traits::MD5Sum< ::jami7095_hw2::EchoString >
template<>
struct MD5Sum< ::jami7095_hw2::EchoStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jami7095_hw2::EchoString >::value();
  }
  static const char* value(const ::jami7095_hw2::EchoStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jami7095_hw2::EchoStringRequest> should match
// service_traits::DataType< ::jami7095_hw2::EchoString >
template<>
struct DataType< ::jami7095_hw2::EchoStringRequest>
{
  static const char* value()
  {
    return DataType< ::jami7095_hw2::EchoString >::value();
  }
  static const char* value(const ::jami7095_hw2::EchoStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jami7095_hw2::EchoStringResponse> should match
// service_traits::MD5Sum< ::jami7095_hw2::EchoString >
template<>
struct MD5Sum< ::jami7095_hw2::EchoStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jami7095_hw2::EchoString >::value();
  }
  static const char* value(const ::jami7095_hw2::EchoStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jami7095_hw2::EchoStringResponse> should match
// service_traits::DataType< ::jami7095_hw2::EchoString >
template<>
struct DataType< ::jami7095_hw2::EchoStringResponse>
{
  static const char* value()
  {
    return DataType< ::jami7095_hw2::EchoString >::value();
  }
  static const char* value(const ::jami7095_hw2::EchoStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAMI7095_HW2_MESSAGE_ECHOSTRING_H
