// Generated by gencpp from file jami7095_hw2/EchoStringResponse.msg
// DO NOT EDIT!


#ifndef JAMI7095_HW2_MESSAGE_ECHOSTRINGRESPONSE_H
#define JAMI7095_HW2_MESSAGE_ECHOSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jami7095_hw2
{
template <class ContainerAllocator>
struct EchoStringResponse_
{
  typedef EchoStringResponse_<ContainerAllocator> Type;

  EchoStringResponse_()
    : echo()  {
    }
  EchoStringResponse_(const ContainerAllocator& _alloc)
    : echo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _echo_type;
  _echo_type echo;





  typedef boost::shared_ptr< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EchoStringResponse_

typedef ::jami7095_hw2::EchoStringResponse_<std::allocator<void> > EchoStringResponse;

typedef boost::shared_ptr< ::jami7095_hw2::EchoStringResponse > EchoStringResponsePtr;
typedef boost::shared_ptr< ::jami7095_hw2::EchoStringResponse const> EchoStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator1> & lhs, const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.echo == rhs.echo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator1> & lhs, const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jami7095_hw2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b400c66aa51415febf8794970de9eb60";
  }

  static const char* value(const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb400c66aa51415feULL;
  static const uint64_t static_value2 = 0xbf8794970de9eb60ULL;
};

template<class ContainerAllocator>
struct DataType< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jami7095_hw2/EchoStringResponse";
  }

  static const char* value(const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string echo\n"
"\n"
;
  }

  static const char* value(const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.echo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EchoStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jami7095_hw2::EchoStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jami7095_hw2::EchoStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "echo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.echo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAMI7095_HW2_MESSAGE_ECHOSTRINGRESPONSE_H
