// Generated by gencpp from file jami7095_hw2/EchoStringRequest.msg
// DO NOT EDIT!


#ifndef JAMI7095_HW2_MESSAGE_ECHOSTRINGREQUEST_H
#define JAMI7095_HW2_MESSAGE_ECHOSTRINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jami7095_hw2
{
template <class ContainerAllocator>
struct EchoStringRequest_
{
  typedef EchoStringRequest_<ContainerAllocator> Type;

  EchoStringRequest_()
    : data()  {
    }
  EchoStringRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EchoStringRequest_

typedef ::jami7095_hw2::EchoStringRequest_<std::allocator<void> > EchoStringRequest;

typedef boost::shared_ptr< ::jami7095_hw2::EchoStringRequest > EchoStringRequestPtr;
typedef boost::shared_ptr< ::jami7095_hw2::EchoStringRequest const> EchoStringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator1> & lhs, const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator1> & lhs, const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jami7095_hw2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jami7095_hw2/EchoStringRequest";
  }

  static const char* value(const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EchoStringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jami7095_hw2::EchoStringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jami7095_hw2::EchoStringRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAMI7095_HW2_MESSAGE_ECHOSTRINGREQUEST_H
